service: tokyo-dome-event-notifyer

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  stage: prod
  region: ap-northeast-1

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  notify:
    handler: bin/handler
    memorySize: 128
    events:
      - schedule: cron(0 21 * * ? *)
    environment:
      SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}
