service: tokyo-dome-event-notifyer

frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  TZ: Asia/Tokyo

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  hello:
    handler: bin/handler
    environment:
      SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}

