service: tokyo-dome-event-notifyer

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  notify:
    handler: bin/handler
    environment:
      SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}
